services:
  postgres:
    image: postgres:latest
    container_name: analytics_db
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
          - postgres-db-volume:/var/lib/postgresql/data
volumes:
  postgres-db-volume: